
rowSums & cbind

```{r}
star_wars_matrix
 #suma de las filas
worldwide_vector <- rowSums(star_wars_matrix)    

 #agregar columnas
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector) 

```
colSums & rbind

```{r}
#suma de las columnas 
total_cols <- colSums(all_wars_matrix)

#agregar filas
totals_matrix <- rbind(all_wars_matrix, total_cols)

#colocar nombre  a la tercera fila y columna
region <- c("US", "non-US", "Total") 
titles <- c("A new hope", "The empire strikes back", "Return of jedi", "Total")

colnames(totals_matrix) <- region
rownames(totals_matrix) <- titles
totals_matrix
totals_matrix[2,1]
totals_matrix[2,]
totals_matrix[2,c(1,2,3)]
totals_matrix[,1]

```
```{r}
totals_matrix[2,]
totals_matrix[,1]

#select one row with row title
row_title <- "The empire strikes back"

#subset evaluate 
subset(totals_matrix, rownames(totals_matrix) %in% row_title)

#select one column with column title
column_title <- "US"
subset(totals_matrix, subset = TRUE, colnames(totals_matrix) %in% column_title)

#select a cell with row title and column title
subset(totals_matrix, rownames(totals_matrix) %in% row_title, colnames(totals_matrix) %in% column_title)

totals_matrix[1:4,]

```
```{r}
star_wars_matrix

new_hope_price <- c(5, 5)
empire_strikes_price <- c(6, 6)
return_jedi_price <- c(7, 7)

price_vector <- c(new_hope_price, empire_strikes_price, return_jedi_price)

ticket_prices_matrix <- matrix(price_vector, byrow = TRUE, nrow = 3)

region <- c("US", "non-US")
titles <- c("A new hope", "The empire strikes back", "Return of jedi")

colnames(ticket_prices_matrix) <- region
rownames(ticket_prices_matrix) <- titles

ticket_prices_matrix

visitors <- star_wars_matrix / ticket_prices_matrix
```
Exercise 
```{r}
u <- c(26:50)
v <- c(51:75)

x <- c(u,v)

w <- matrix(x, byrow = TRUE, ncol = 5)

w[2,3]
w
w[1:10,3:4]
```

Factor 
```{r}
# Lo que hace es agrupar y reconoce las categorias

sex_vector <- c("Male","Female","Female","Male","Male")
factor_sex_vector <- factor(sex_vector)

temperature_vector <- c("High", "Low", "High", "Low", "Medium")
factor_temperature_vector <- factor(temperature_vector)

factor_temperature_vector <- factor(temperature_vector, order=TRUE, levels = c ("Low","Medium","High"))

factor_temperature_vector[1] > factor_temperature_vector[2]

```
```{r}
survey_vector <- c("M", "F", "F", "M", "M")

#Nosotros definimos el orden
#factor_survey_vector <- factor(survey_vector)
factor_survey_vector <- factor(survey_vector, order=TRUE, levels = c("M","F"))

#levels(factor_survey_vector) <- c("Female", "Male")
levels(factor_survey_vector) <- c("Male", "Female")
factor_survey_vector

male <- factor_survey_vector[1]
female <- factor_survey_vector[2]

male > female
```
Summary
```{r}
#Resumen de las categorias
summary(factor_survey_vector)
summary(survey_vector)
```
Dataframes

```{r}
mtcars
```

```{r}
head(mtcars)
```

```{r}
str(mtcars)
```
Creating a dataframe

```{r}
#vector de cada columna del dataframe
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

planets_df <- data.frame(name, type, diameter, rotation, rings)
```


```{r}
str(planets_df)
```


```{r}
planets_df[1,3]                          #Indices
planets_df[1,3:5]
planets_df[1:5,3:5]
planets_df[,3:5]
planets_df[1:4,"diameter"]               #Nombres
planets_df[1:4,c("diameter","rotation")]
rings_vector <- planets_df$rings         #Columna que quiero
planets_df[rings_vector,]                #Donde tenga valor verdadero
planets_df[!rings_vector,]               #Donde tenga valor falso
planets_df[,]                            #Donde tenga todo

subset(planets_df, subset = diameter < 1) #Crear condiciones y filtrado
subset(planets_df, subset = rings == TRUE)
subset(planets_df, subset = rings == 1)
subset(planets_df, subset = rings == 0)
```

Sorting 

```{r}

planets_df
positions <- order(planets_df$diameter)

planets_df[positions, 2:3] #fila se ordene y la columna 2 y 3
```


