Intro to basic

```{r}
3 + 4
6 + 12
1 + 7
1 + 2 + 5 + 7

5-5
3*5
(5+5)/2
2^5
28%%6
```
Variables
```{r}
my_var <- 10
my_var <- 20
my_var <- "Hello world"

my_var

my_apples <- 5
my_oranges <-6

my_apples + my_oranges
my_fruit <- my_apples + my_oranges

test <- 1


```
Basic data types in R

```{r}
my_numeric <- 42
my_float <- 5.2
my_character <- "universe"
my_logical <- FALSE 

class(my_numeric)
```
Vectors

```{r}
c(1,2,3)
numeric_vector <- c(1,2,3)
class(numeric_vector)

character_vector <- c("a","b","c")
boolean_vector <- c(TRUE,FALSE,TRUE)

vector_range <- c(1:100)

```
Exercise 

```{r}
my_numeric_vector <- c(1:12)

my_character_vector <- c("Amilcar","Alexander","Cristian","Joel","Luis")
```
Naming vector 

```{r}
poker_vector <- c(140,80,20,55,60)
roulette_vector <- c(24,6,100,87,45)

names(poker_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
names(roulette_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")

poker_vector
roulette_vector

#names_vector <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
#names(poker_vector) <- names_vector
#names(roulette_vector) <- names_vector
```
Calculating

```{r}
total_daily <- poker_vector + roulette_vector

poker_vector
roulette_vector
total_daily

poker_vector
total_poker <- sum(poker_vector)
total_roulette <- sum(roulette_vector)

total_poker
total_roulette

total_week <- total_poker + total_roulette

```
Vector Selection

```{r}
poker_wednesday <- poker_vector[3]

poker_midweek <- poker_vector[c(2,3,4)]
poker_vector[c(1,3,5)]

# slicing
roulette_selection_vector <- roulette_vector[2:4]

poker_start <- poker_vector[c("Monday","Tuesday","Wednesday")]

poker_start
sum(poker_start)

poker_vector[3] = 40
poker_vector[c(2,3,4)] = c(85,70,10)

poker_1_5 <-poker_vector[1:5]
poker_3 <- poker_1_5[c(1:2, 4:5)]

```
Selection by comparison
```{r}
selection_vector <- poker_vector > 75                 # <
poker_winning_day <- poker_vector[selection_vector]   # [!selection_vector]



```

Exercise 
```{r}
x <- c(5,10,15,20,28)
y <- c(1,2,3,4,28)

menor <- x < y
mayor <- x > y
igual <- x == y
result <- x * y
suma <- x + y

length(x) == length(y)

length(poker_vector) 

```
Matrices
```{r}
matrix(1:9, byrow = TRUE, nrow = 3)
```
Naming a matrix

```{r}
new_hope <- c(460.99, 314.4)
empire_strikes <- c(290.47, 247.9)
return_jedi <- c(309.3, 165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)

star_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)

region <- c("US", "non-US")
titles <- c("A new hope", "The empire strikes back", "Return of jedi")

colnames(star_wars_matrix) <- region
rownames(star_wars_matrix) <- titles
```


